name: Build Multi-Arch Docker Image

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: 'Caddy version'
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      CADDY_VERSION: ${{ inputs.caddy_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
# TODO:
# push to ghcr.io
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            myrepo/myimage:${{ env.CADDY_VERSION }}-${{ github.run_id }}
            myrepo/myimage:pre

      - name: Output image digest
        run: echo ${{ steps.docker_build.outputs.digest }}