---
name: Image Prune
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # every week

permissions:
  contents: read
  packages: write

concurrency:
  group: image-prune
  cancel-in-progress: true

jobs:
  clean-untagged:
    runs-on: ubuntu-24.04
    name: Delete untagged images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.CLEANER_TOKEN }}
          image-names: "u4dav"
          tag-selection: untagged
          cut-off: 1h

  clean-edge:
    needs: clean-untagged
    runs-on: ubuntu-24.04
    name: Delete old edge images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.CLEANER_TOKEN }}
          image-names: "u4dav"
          image-tags: "edge*"
          tag-selection: tagged
          cut-off: 1h  # delete images older than 1 hour
          dry-run: true

  clean-pr:
    needs: clean-edge
    runs-on: ubuntu-24.04
    name: Delete old PR images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.CLEANER_TOKEN }}
          image-names: "u4dav"
          image-tags: "pr-*"
          tag-selection: tagged
          cut-off: 1h  # delete images older than 1 hour
          dry-run: true
