---
name: Track Caddy Releases

on:
  schedule:
    - cron: "0 0 * * 0" # every week
  workflow_dispatch:

concurrency:
  group: caddy-release
  cancel-in-progress: true

jobs:
  get-latest-caddy:
    runs-on: ubuntu-24.04
    name: Get latest Caddy version
    outputs:
      caddy-version: ${{ steps.caddy-version.outputs.result }}
      caddy-tag: ${{ steps.caddy-tag.outputs.caddy-tag }}
      new-version: ${{ steps.check-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest
        uses: actions/github-script@v7
        id: caddy-version
        with:
          result-encoding: string
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'caddyserver',
              repo: 'caddy'
            });

            return response.data.tag_name.startsWith('v') ? response.data.tag_name.substring(1) : response.data.tag_name;

      - name: Print Caddy version
        id: caddy-tag
        run: |
          echo "Caddy version is ${{ steps.caddy-version.outputs.result }}"
          {
            echo "caddy-tag=v${{ steps.caddy-version.outputs.result }}"
          } >> "$GITHUB_OUTPUT"

      - name: Check if version exists
        id: check-version
        run: |
          VERSION_EXISTS=$(git tag -l "${{ steps.caddy-tag.outputs.caddy-tag }}")
          if [ -z "$VERSION_EXISTS" ]; then
            echo "new-version=true" >> "$GITHUB_OUTPUT"
          fi

  commit-new-version:
    runs-on: ubuntu-24.04
    name: Commit new version
    needs: get-latest-caddy
    if: ${{ needs.get-latest-caddy.outputs.new-version == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo new version
        run: echo "${{ needs.get-latest-caddy.outputs.caddy-version }}" > CADDY_VERSION

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update Caddy to ${{ needs.get-latest-caddy.outputs.caddy-version }}"
          add: CADDY_VERSION
          push: true

  create-release:
    runs-on: ubuntu-24.04
    name: Create release
    needs:
      - commit-new-version
      - get-latest-caddy
    if: ${{ needs.get-latest-caddy.outputs.new-version == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          draft: false
          make_latest: true
          tag_name: ${{ needs.get-latest-caddy.outputs.caddy-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Caddy version ${{ needs.get-latest-caddy.outputs.caddy-version }}"

  call-publish:
    runs-on: ubuntu-24.04
    name: Call publish
    needs: create-release
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: write
    steps:
    - name: Call Docker Publish Workflow
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'docker-publish.yml',
            ref: context.ref
          });
